language: erlang
otp_release:
    - 17.0-rc1
before_install:
    - git clone https://github.com/elixir-lang/elixir
    - cd elixir && git checkout v0.13 && make && cd ..
before_script:
    - export PATH=`pwd`/elixir/bin:$PATH
    - MIX_ENV=test mix do deps.get
    - MIX_ENV=test mix do deps.update --all
    - MIX_ENV=test mix do deps.compile
    - MIX_ENV=test mix do deps.compile meck
script:
    - MIX_ENV=test mix amrita --trace