language: elixir
env:
  - MIX_ENV=test
elixir:
  - 1.18.2
otp_release:
  - 27.2
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
after_success:
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix coveralls.travis
